/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;

import com.example.*;
import com.example.models.*;
import com.example.exceptions.*;
import com.example.http.client.HttpClient;
import com.example.http.client.HttpContext;
import com.example.http.request.HttpRequest;
import com.example.http.response.HttpResponse;
import com.example.http.response.HttpStringResponse;
import com.example.http.client.APICallBack;
import com.example.controllers.syncwrapper.APICallBackCatcher;

public class DeliveryAPIController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static DeliveryAPIController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the DeliveryAPIController class 
     */
    public static DeliveryAPIController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new DeliveryAPIController();
                }
            }
        }
        return instance;
    }

    /**
     * GetResources
     * @param    body    Required parameter: { SRNS*, TargetRegionID }
     * @return    Returns the GetResourceResponse response from the API call 
     */
    public GetResourceResponse createGetResources(
                final GetResourceRequest body
    ) throws Throwable {

        HttpRequest _request = _buildCreateGetResourcesRequest(body);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleCreateGetResourcesResponse(_context);
    }

    /**
     * GetResources
     * @param    body    Required parameter: { SRNS*, TargetRegionID }
     */
    public void createGetResourcesAsync(
                final GetResourceRequest body,
                final APICallBack<GetResourceResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildCreateGetResourcesRequest(body);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            GetResourceResponse returnValue = _handleCreateGetResourcesResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for createGetResources
     */
    private HttpRequest _buildCreateGetResourcesRequest(
                final GetResourceRequest body) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/GetResources");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");
        _headers.put("content-type", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().postBody(_queryUrl, _headers, APIHelper.serialize(body));

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for createGetResources
     * @return An object of type GetResourceResponse
     */
    private GetResourceResponse _handleCreateGetResourcesResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 400) {
            throw new GenericResponseErrorException("BAD_REQUEST", _context);
        }
        if (_responseCode == 500) {
            throw new ErrorResponseException("INTERNAL_SERVER_ERROR", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        GetResourceResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<GetResourceResponse>(){});

        return _result;
    }

}
