/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Body6Builder {
    //the instance to build
    private Body6 body6;

    /**
     * Default constructor to initialize the instance
     */
    public Body6Builder() {
        body6 = new Body6();
    }

    public Body6Builder parentWorkflowID(String parentWorkflowID) {
        body6.setParentWorkflowID(parentWorkflowID);
        return this;
    }

    public Body6Builder userEmail(String userEmail) {
        body6.setUserEmail(userEmail);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body6 build() {
        return body6;
    }
}