/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Body6 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1661310160119485792L;
    private String parentWorkflowID;
    private String userEmail;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ParentWorkflowID")
    public String getParentWorkflowID ( ) { 
        return this.parentWorkflowID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ParentWorkflowID")
    public void setParentWorkflowID (String value) { 
        this.parentWorkflowID = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("UserEmail")
    public String getUserEmail ( ) { 
        return this.userEmail;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("UserEmail")
    public void setUserEmail (String value) { 
        this.userEmail = value;
    }
 
}
