/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Body4Builder {
    //the instance to build
    private Body4 body4;

    /**
     * Default constructor to initialize the instance
     */
    public Body4Builder() {
        body4 = new Body4();
    }

    public Body4Builder id(String id) {
        body4.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body4 build() {
        return body4;
    }
}