/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Body2 
        implements java.io.Serializable {
    private static final long serialVersionUID = 116015342094495829L;
    private String ownerID;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("OwnerID")
    public String getOwnerID ( ) { 
        return this.ownerID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("OwnerID")
    public void setOwnerID (String value) { 
        this.ownerID = value;
    }
 
}
