/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Body5 
        implements java.io.Serializable {
    private static final long serialVersionUID = 116002782777585434L;
    private String workflowID;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("WorkflowID")
    public String getWorkflowID ( ) { 
        return this.workflowID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("WorkflowID")
    public void setWorkflowID (String value) { 
        this.workflowID = value;
    }
 
}
