/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Body3Builder {
    //the instance to build
    private Body3 body3;

    /**
     * Default constructor to initialize the instance
     */
    public Body3Builder() {
        body3 = new Body3();
    }

    public Body3Builder manifestFolderPath(String manifestFolderPath) {
        body3.setManifestFolderPath(manifestFolderPath);
        return this;
    }

    public Body3Builder filesToProcess(Integer filesToProcess) {
        body3.setFilesToProcess(filesToProcess);
        return this;
    }

    public Body3Builder pipelineID(String pipelineID) {
        body3.setPipelineID(pipelineID);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body3 build() {
        return body3;
    }
}