/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Body7Builder {
    //the instance to build
    private Body7 body7;

    /**
     * Default constructor to initialize the instance
     */
    public Body7Builder() {
        body7 = new Body7();
    }

    public Body7Builder id(String id) {
        body7.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body7 build() {
        return body7;
    }
}