/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Body5Builder {
    //the instance to build
    private Body5 body5;

    /**
     * Default constructor to initialize the instance
     */
    public Body5Builder() {
        body5 = new Body5();
    }

    public Body5Builder workflowID(String workflowID) {
        body5.setWorkflowID(workflowID);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body5 build() {
        return body5;
    }
}