/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Body10Builder {
    //the instance to build
    private Body10 body10;

    /**
     * Default constructor to initialize the instance
     */
    public Body10Builder() {
        body10 = new Body10();
    }

    public Body10Builder pipelineId(String pipelineId) {
        body10.setPipelineId(pipelineId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body10 build() {
        return body10;
    }
}