/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Body3 
        implements java.io.Serializable {
    private static final long serialVersionUID = -999449801582216944L;
    private String manifestFolderPath;
    private Integer filesToProcess;
    private String pipelineID;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ManifestFolderPath")
    public String getManifestFolderPath ( ) { 
        return this.manifestFolderPath;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ManifestFolderPath")
    public void setManifestFolderPath (String value) { 
        this.manifestFolderPath = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("FilesToProcess")
    public Integer getFilesToProcess ( ) { 
        return this.filesToProcess;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("FilesToProcess")
    public void setFilesToProcess (Integer value) { 
        this.filesToProcess = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("PipelineID")
    public String getPipelineID ( ) { 
        return this.pipelineID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("PipelineID")
    public void setPipelineID (String value) { 
        this.pipelineID = value;
    }
 
}
