/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Body10 
        implements java.io.Serializable {
    private static final long serialVersionUID = -116084613276751602L;
    private String pipelineId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("pipelineId")
    public String getPipelineId ( ) { 
        return this.pipelineId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("pipelineId")
    public void setPipelineId (String value) { 
        this.pipelineId = value;
    }
 
}
