/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CollectionUpdateBuilder {
    //the instance to build
    private CollectionUpdate collectionUpdate;

    /**
     * Default constructor to initialize the instance
     */
    public CollectionUpdateBuilder() {
        collectionUpdate = new CollectionUpdate();
    }

    public CollectionUpdateBuilder ownerID(String ownerID) {
        collectionUpdate.setOwnerID(ownerID);
        return this;
    }

    public CollectionUpdateBuilder name(String name) {
        collectionUpdate.setName(name);
        return this;
    }

    public CollectionUpdateBuilder description(String description) {
        collectionUpdate.setDescription(description);
        return this;
    }

    public CollectionUpdateBuilder workSpaceID(String workSpaceID) {
        collectionUpdate.setWorkSpaceID(workSpaceID);
        return this;
    }

    public CollectionUpdateBuilder sRN(String sRN) {
        collectionUpdate.setSRN(sRN);
        return this;
    }

    public CollectionUpdateBuilder resources(List<String> resources) {
        collectionUpdate.setResources(resources);
        return this;
    }

    public CollectionUpdateBuilder filterSpecification(List<String> filterSpecification) {
        collectionUpdate.setFilterSpecification(filterSpecification);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CollectionUpdate build() {
        return collectionUpdate;
    }
}