/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CollectionCreateBuilder {
    //the instance to build
    private CollectionCreate collectionCreate;

    /**
     * Default constructor to initialize the instance
     */
    public CollectionCreateBuilder() {
        collectionCreate = new CollectionCreate();
    }

    public CollectionCreateBuilder ownerID(String ownerID) {
        collectionCreate.setOwnerID(ownerID);
        return this;
    }

    public CollectionCreateBuilder name(String name) {
        collectionCreate.setName(name);
        return this;
    }

    public CollectionCreateBuilder description(String description) {
        collectionCreate.setDescription(description);
        return this;
    }

    public CollectionCreateBuilder workSpaceID(String workSpaceID) {
        collectionCreate.setWorkSpaceID(workSpaceID);
        return this;
    }

    public CollectionCreateBuilder resources(List<String> resources) {
        collectionCreate.setResources(resources);
        return this;
    }

    public CollectionCreateBuilder filterSpecification(List<String> filterSpecification) {
        collectionCreate.setFilterSpecification(filterSpecification);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CollectionCreate build() {
        return collectionCreate;
    }
}