/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class DescribeWorkflowPayloadBuilder {
    //the instance to build
    private DescribeWorkflowPayload describeWorkflowPayload;

    /**
     * Default constructor to initialize the instance
     */
    public DescribeWorkflowPayloadBuilder() {
        describeWorkflowPayload = new DescribeWorkflowPayload();
    }

    public DescribeWorkflowPayloadBuilder workflowJobID(String workflowJobID) {
        describeWorkflowPayload.setWorkflowJobID(workflowJobID);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DescribeWorkflowPayload build() {
        return describeWorkflowPayload;
    }
}