/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class DescribeWorkflowResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1392475815184839995L;
    private String runStart;
    private String runEnd;
    private Integer durationInMs;
    private String workflowStage;
    private String reason;
    private String workflowJobID;
    private String lastUpdateDate;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("RunStart")
    public String getRunStart ( ) { 
        return this.runStart;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("RunStart")
    public void setRunStart (String value) { 
        this.runStart = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("RunEnd")
    public String getRunEnd ( ) { 
        return this.runEnd;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("RunEnd")
    public void setRunEnd (String value) { 
        this.runEnd = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("DurationInMs")
    public Integer getDurationInMs ( ) { 
        return this.durationInMs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("DurationInMs")
    public void setDurationInMs (Integer value) { 
        this.durationInMs = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("WorkflowStage")
    public String getWorkflowStage ( ) { 
        return this.workflowStage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("WorkflowStage")
    public void setWorkflowStage (String value) { 
        this.workflowStage = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Reason")
    public String getReason ( ) { 
        return this.reason;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Reason")
    public void setReason (String value) { 
        this.reason = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("WorkflowJobID")
    public String getWorkflowJobID ( ) { 
        return this.workflowJobID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("WorkflowJobID")
    public void setWorkflowJobID (String value) { 
        this.workflowJobID = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("LastUpdateDate")
    public String getLastUpdateDate ( ) { 
        return this.lastUpdateDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("LastUpdateDate")
    public void setLastUpdateDate (String value) { 
        this.lastUpdateDate = value;
    }
 
}
