/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class DescribeWorkflowPayload 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5982178948190612L;
    private String workflowJobID;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("WorkflowJobID")
    public String getWorkflowJobID ( ) { 
        return this.workflowJobID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("WorkflowJobID")
    public void setWorkflowJobID (String value) { 
        this.workflowJobID = value;
    }
 
}
