/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class DescribeWorkflowResponseBuilder {
    //the instance to build
    private DescribeWorkflowResponse describeWorkflowResponse;

    /**
     * Default constructor to initialize the instance
     */
    public DescribeWorkflowResponseBuilder() {
        describeWorkflowResponse = new DescribeWorkflowResponse();
    }

    public DescribeWorkflowResponseBuilder runStart(String runStart) {
        describeWorkflowResponse.setRunStart(runStart);
        return this;
    }

    public DescribeWorkflowResponseBuilder runEnd(String runEnd) {
        describeWorkflowResponse.setRunEnd(runEnd);
        return this;
    }

    public DescribeWorkflowResponseBuilder durationInMs(Integer durationInMs) {
        describeWorkflowResponse.setDurationInMs(durationInMs);
        return this;
    }

    public DescribeWorkflowResponseBuilder workflowStage(String workflowStage) {
        describeWorkflowResponse.setWorkflowStage(workflowStage);
        return this;
    }

    public DescribeWorkflowResponseBuilder reason(String reason) {
        describeWorkflowResponse.setReason(reason);
        return this;
    }

    public DescribeWorkflowResponseBuilder workflowJobID(String workflowJobID) {
        describeWorkflowResponse.setWorkflowJobID(workflowJobID);
        return this;
    }

    public DescribeWorkflowResponseBuilder lastUpdateDate(String lastUpdateDate) {
        describeWorkflowResponse.setLastUpdateDate(lastUpdateDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DescribeWorkflowResponse build() {
        return describeWorkflowResponse;
    }
}