/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GenericResetResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5412522490301493879L;
    private String message;
    private Object cosmosDBResults;
    private Object ingestionRulesResults;
    private Object elasticSearchIndexResults;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Message")
    public void setMessage (String value) { 
        this.message = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CosmosDB results")
    public Object getCosmosDBResults ( ) { 
        return this.cosmosDBResults;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CosmosDB results")
    public void setCosmosDBResults (Object value) { 
        this.cosmosDBResults = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("IngestionRules results")
    public Object getIngestionRulesResults ( ) { 
        return this.ingestionRulesResults;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("IngestionRules results")
    public void setIngestionRulesResults (Object value) { 
        this.ingestionRulesResults = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Elastic Search Index results")
    public Object getElasticSearchIndexResults ( ) { 
        return this.elasticSearchIndexResults;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Elastic Search Index results")
    public void setElasticSearchIndexResults (Object value) { 
        this.elasticSearchIndexResults = value;
    }
 
}
