/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class GenericResponse200Builder {
    //the instance to build
    private GenericResponse200 genericResponse200;

    /**
     * Default constructor to initialize the instance
     */
    public GenericResponse200Builder() {
        genericResponse200 = new GenericResponse200();
    }

    public GenericResponse200Builder status(String status) {
        genericResponse200.setStatus(status);
        return this;
    }

    public GenericResponse200Builder workflowId(String workflowId) {
        genericResponse200.setWorkflowId(workflowId);
        return this;
    }

    public GenericResponse200Builder message(String message) {
        genericResponse200.setMessage(message);
        return this;
    }

    public GenericResponse200Builder code(String code) {
        genericResponse200.setCode(code);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GenericResponse200 build() {
        return genericResponse200;
    }
}