/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class GenericResetResponseBuilder {
    //the instance to build
    private GenericResetResponse genericResetResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GenericResetResponseBuilder() {
        genericResetResponse = new GenericResetResponse();
    }

    public GenericResetResponseBuilder message(String message) {
        genericResetResponse.setMessage(message);
        return this;
    }

    public GenericResetResponseBuilder cosmosDBResults(Object cosmosDBResults) {
        genericResetResponse.setCosmosDBResults(cosmosDBResults);
        return this;
    }

    public GenericResetResponseBuilder ingestionRulesResults(Object ingestionRulesResults) {
        genericResetResponse.setIngestionRulesResults(ingestionRulesResults);
        return this;
    }

    public GenericResetResponseBuilder elasticSearchIndexResults(Object elasticSearchIndexResults) {
        genericResetResponse.setElasticSearchIndexResults(elasticSearchIndexResults);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GenericResetResponse build() {
        return genericResetResponse;
    }
}