/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class GenericResponseBuilder {
    //the instance to build
    private GenericResponse genericResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GenericResponseBuilder() {
        genericResponse = new GenericResponse();
    }

    public GenericResponseBuilder status(String status) {
        genericResponse.setStatus(status);
        return this;
    }

    public GenericResponseBuilder message(String message) {
        genericResponse.setMessage(message);
        return this;
    }

    public GenericResponseBuilder code(String code) {
        genericResponse.setCode(code);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GenericResponse build() {
        return genericResponse;
    }
}