/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetResourceResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7628728024008130990L;
    private List<String> unprocessedSRNs;
    private List<GetResourceObject> result;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("UnprocessedSRNs")
    public List<String> getUnprocessedSRNs ( ) { 
        return this.unprocessedSRNs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("UnprocessedSRNs")
    public void setUnprocessedSRNs (List<String> value) { 
        this.unprocessedSRNs = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Result")
    public List<GetResourceObject> getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Result")
    public void setResult (List<GetResourceObject> value) { 
        this.result = value;
    }
 
}
