/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetResourceObject 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2368856171932051533L;
    private String sRN;
    private Object data;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SRN")
    public String getSRN ( ) { 
        return this.sRN;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SRN")
    public void setSRN (String value) { 
        this.sRN = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Data")
    public Object getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Data")
    public void setData (Object value) { 
        this.data = value;
    }
 
}
