/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetResourceRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5749689025635168142L;
    private List<String> sRNS;
    private String targetRegionID;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SRNS")
    public List<String> getSRNS ( ) { 
        return this.sRNS;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SRNS")
    public void setSRNS (List<String> value) { 
        this.sRNS = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("TargetRegionID")
    public String getTargetRegionID ( ) { 
        return this.targetRegionID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("TargetRegionID")
    public void setTargetRegionID (String value) { 
        this.targetRegionID = value;
    }
 
}
