/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class GetResourceRequestBuilder {
    //the instance to build
    private GetResourceRequest getResourceRequest;

    /**
     * Default constructor to initialize the instance
     */
    public GetResourceRequestBuilder() {
        getResourceRequest = new GetResourceRequest();
    }

    public GetResourceRequestBuilder sRNS(List<String> sRNS) {
        getResourceRequest.setSRNS(sRNS);
        return this;
    }

    public GetResourceRequestBuilder targetRegionID(String targetRegionID) {
        getResourceRequest.setTargetRegionID(targetRegionID);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetResourceRequest build() {
        return getResourceRequest;
    }
}