/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class InlineResponse2001 
        implements java.io.Serializable {
    private static final long serialVersionUID = -26185303696959020L;
    private String parentWorkflowId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("parentWorkflowId")
    public String getParentWorkflowId ( ) { 
        return this.parentWorkflowId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("parentWorkflowId")
    public void setParentWorkflowId (String value) { 
        this.parentWorkflowId = value;
    }
 
}
