/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class InlineResponse2001Builder {
    //the instance to build
    private InlineResponse2001 inlineResponse2001;

    /**
     * Default constructor to initialize the instance
     */
    public InlineResponse2001Builder() {
        inlineResponse2001 = new InlineResponse2001();
    }

    public InlineResponse2001Builder parentWorkflowId(String parentWorkflowId) {
        inlineResponse2001.setParentWorkflowId(parentWorkflowId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InlineResponse2001 build() {
        return inlineResponse2001;
    }
}