/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class InlineResponse200Builder {
    //the instance to build
    private InlineResponse200 inlineResponse200;

    /**
     * Default constructor to initialize the instance
     */
    public InlineResponse200Builder() {
        inlineResponse200 = new InlineResponse200();
    }

    public InlineResponse200Builder sRN(String sRN) {
        inlineResponse200.setSRN(sRN);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InlineResponse200 build() {
        return inlineResponse200;
    }
}