/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class MCollection 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4798543567119954021L;
    private String ownerID;
    private String name;
    private String description;
    private String workSpaceID;
    private String sRN;
    private List<String> resources;
    private List<String> filterSpecification;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("OwnerID")
    public String getOwnerID ( ) { 
        return this.ownerID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("OwnerID")
    public void setOwnerID (String value) { 
        this.ownerID = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("WorkSpaceID")
    public String getWorkSpaceID ( ) { 
        return this.workSpaceID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("WorkSpaceID")
    public void setWorkSpaceID (String value) { 
        this.workSpaceID = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SRN")
    public String getSRN ( ) { 
        return this.sRN;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SRN")
    public void setSRN (String value) { 
        this.sRN = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Resources")
    public List<String> getResources ( ) { 
        return this.resources;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Resources")
    public void setResources (List<String> value) { 
        this.resources = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("FilterSpecification")
    public List<String> getFilterSpecification ( ) { 
        return this.filterSpecification;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("FilterSpecification")
    public void setFilterSpecification (List<String> value) { 
        this.filterSpecification = value;
    }
 
}
