/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class MCollectionBuilder {
    //the instance to build
    private MCollection mCollection;

    /**
     * Default constructor to initialize the instance
     */
    public MCollectionBuilder() {
        mCollection = new MCollection();
    }

    public MCollectionBuilder ownerID(String ownerID) {
        mCollection.setOwnerID(ownerID);
        return this;
    }

    public MCollectionBuilder name(String name) {
        mCollection.setName(name);
        return this;
    }

    public MCollectionBuilder description(String description) {
        mCollection.setDescription(description);
        return this;
    }

    public MCollectionBuilder workSpaceID(String workSpaceID) {
        mCollection.setWorkSpaceID(workSpaceID);
        return this;
    }

    public MCollectionBuilder sRN(String sRN) {
        mCollection.setSRN(sRN);
        return this;
    }

    public MCollectionBuilder resources(List<String> resources) {
        mCollection.setResources(resources);
        return this;
    }

    public MCollectionBuilder filterSpecification(List<String> filterSpecification) {
        mCollection.setFilterSpecification(filterSpecification);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MCollection build() {
        return mCollection;
    }
}