/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ParentWorkflowBuilder {
    //the instance to build
    private ParentWorkflow parentWorkflow;

    /**
     * Default constructor to initialize the instance
     */
    public ParentWorkflowBuilder() {
        parentWorkflow = new ParentWorkflow();
    }

    public ParentWorkflowBuilder id(String id) {
        parentWorkflow.setId(id);
        return this;
    }

    public ParentWorkflowBuilder inProgress(Integer inProgress) {
        parentWorkflow.setInProgress(inProgress);
        return this;
    }

    public ParentWorkflowBuilder endDate(String endDate) {
        parentWorkflow.setEndDate(endDate);
        return this;
    }

    public ParentWorkflowBuilder notStarted(Integer notStarted) {
        parentWorkflow.setNotStarted(notStarted);
        return this;
    }

    public ParentWorkflowBuilder failed(Integer failed) {
        parentWorkflow.setFailed(failed);
        return this;
    }

    public ParentWorkflowBuilder success(Integer success) {
        parentWorkflow.setSuccess(success);
        return this;
    }

    public ParentWorkflowBuilder preIngestionError(Integer preIngestionError) {
        parentWorkflow.setPreIngestionError(preIngestionError);
        return this;
    }

    public ParentWorkflowBuilder totalFiles(Integer totalFiles) {
        parentWorkflow.setTotalFiles(totalFiles);
        return this;
    }

    public ParentWorkflowBuilder type(String type) {
        parentWorkflow.setType(type);
        return this;
    }

    public ParentWorkflowBuilder workflowComplete(Boolean workflowComplete) {
        parentWorkflow.setWorkflowComplete(workflowComplete);
        return this;
    }

    public ParentWorkflowBuilder pipelineId(String pipelineId) {
        parentWorkflow.setPipelineId(pipelineId);
        return this;
    }

    public ParentWorkflowBuilder environment(String environment) {
        parentWorkflow.setEnvironment(environment);
        return this;
    }

    public ParentWorkflowBuilder createdDate(String createdDate) {
        parentWorkflow.setCreatedDate(createdDate);
        return this;
    }

    public ParentWorkflowBuilder sourceApplication(String sourceApplication) {
        parentWorkflow.setSourceApplication(sourceApplication);
        return this;
    }

    public ParentWorkflowBuilder createdBy(String createdBy) {
        parentWorkflow.setCreatedBy(createdBy);
        return this;
    }

    public ParentWorkflowBuilder preIngestionErrors(List<Object> preIngestionErrors) {
        parentWorkflow.setPreIngestionErrors(preIngestionErrors);
        return this;
    }

    public ParentWorkflowBuilder failedWorkflows(List<Object> failedWorkflows) {
        parentWorkflow.setFailedWorkflows(failedWorkflows);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ParentWorkflow build() {
        return parentWorkflow;
    }
}