/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ParentWorkflow 
        implements java.io.Serializable {
    private static final long serialVersionUID = 9045025150539957934L;
    private String id;
    private Integer inProgress;
    private String endDate;
    private Integer notStarted;
    private Integer failed;
    private Integer success;
    private Integer preIngestionError;
    private Integer totalFiles;
    private String type;
    private Boolean workflowComplete;
    private String pipelineId;
    private String environment;
    private String createdDate;
    private String sourceApplication;
    private String createdBy;
    private List<Object> preIngestionErrors;
    private List<Object> failedWorkflows;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("inProgress")
    public Integer getInProgress ( ) { 
        return this.inProgress;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("inProgress")
    public void setInProgress (Integer value) { 
        this.inProgress = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("endDate")
    public String getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("endDate")
    public void setEndDate (String value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("notStarted")
    public Integer getNotStarted ( ) { 
        return this.notStarted;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("notStarted")
    public void setNotStarted (Integer value) { 
        this.notStarted = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("failed")
    public Integer getFailed ( ) { 
        return this.failed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("failed")
    public void setFailed (Integer value) { 
        this.failed = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("success")
    public Integer getSuccess ( ) { 
        return this.success;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("success")
    public void setSuccess (Integer value) { 
        this.success = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("preIngestionError")
    public Integer getPreIngestionError ( ) { 
        return this.preIngestionError;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("preIngestionError")
    public void setPreIngestionError (Integer value) { 
        this.preIngestionError = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("totalFiles")
    public Integer getTotalFiles ( ) { 
        return this.totalFiles;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("totalFiles")
    public void setTotalFiles (Integer value) { 
        this.totalFiles = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("workflowComplete")
    public Boolean getWorkflowComplete ( ) { 
        return this.workflowComplete;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("workflowComplete")
    public void setWorkflowComplete (Boolean value) { 
        this.workflowComplete = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("pipelineId")
    public String getPipelineId ( ) { 
        return this.pipelineId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("pipelineId")
    public void setPipelineId (String value) { 
        this.pipelineId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("environment")
    public String getEnvironment ( ) { 
        return this.environment;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("environment")
    public void setEnvironment (String value) { 
        this.environment = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createdDate")
    public String getCreatedDate ( ) { 
        return this.createdDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createdDate")
    public void setCreatedDate (String value) { 
        this.createdDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sourceApplication")
    public String getSourceApplication ( ) { 
        return this.sourceApplication;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sourceApplication")
    public void setSourceApplication (String value) { 
        this.sourceApplication = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createdBy")
    public String getCreatedBy ( ) { 
        return this.createdBy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createdBy")
    public void setCreatedBy (String value) { 
        this.createdBy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("preIngestionErrors")
    public List<Object> getPreIngestionErrors ( ) { 
        return this.preIngestionErrors;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("preIngestionErrors")
    public void setPreIngestionErrors (List<Object> value) { 
        this.preIngestionErrors = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("failedWorkflows")
    public List<Object> getFailedWorkflows ( ) { 
        return this.failedWorkflows;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("failedWorkflows")
    public void setFailedWorkflows (List<Object> value) { 
        this.failedWorkflows = value;
    }
 
}
