/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class PipelineCreateBuilder {
    //the instance to build
    private PipelineCreate pipelineCreate;

    /**
     * Default constructor to initialize the instance
     */
    public PipelineCreateBuilder() {
        pipelineCreate = new PipelineCreate();
    }

    public PipelineCreateBuilder pipelineName(String pipelineName) {
        pipelineCreate.setPipelineName(pipelineName);
        return this;
    }

    public PipelineCreateBuilder description(String description) {
        pipelineCreate.setDescription(description);
        return this;
    }

    public PipelineCreateBuilder createdBy(String createdBy) {
        pipelineCreate.setCreatedBy(createdBy);
        return this;
    }

    public PipelineCreateBuilder manifestFolderPath(String manifestFolderPath) {
        pipelineCreate.setManifestFolderPath(manifestFolderPath);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PipelineCreate build() {
        return pipelineCreate;
    }
}