/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class PipelineGenericResponseBuilder {
    //the instance to build
    private PipelineGenericResponse pipelineGenericResponse;

    /**
     * Default constructor to initialize the instance
     */
    public PipelineGenericResponseBuilder() {
        pipelineGenericResponse = new PipelineGenericResponse();
    }

    public PipelineGenericResponseBuilder status(String status) {
        pipelineGenericResponse.setStatus(status);
        return this;
    }

    public PipelineGenericResponseBuilder message(String message) {
        pipelineGenericResponse.setMessage(message);
        return this;
    }

    public PipelineGenericResponseBuilder id(String id) {
        pipelineGenericResponse.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PipelineGenericResponse build() {
        return pipelineGenericResponse;
    }
}