/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class PipelineUpdateBuilder {
    //the instance to build
    private PipelineUpdate pipelineUpdate;

    /**
     * Default constructor to initialize the instance
     */
    public PipelineUpdateBuilder() {
        pipelineUpdate = new PipelineUpdate();
    }

    public PipelineUpdateBuilder id(String id) {
        pipelineUpdate.setId(id);
        return this;
    }

    public PipelineUpdateBuilder pipelineName(String pipelineName) {
        pipelineUpdate.setPipelineName(pipelineName);
        return this;
    }

    public PipelineUpdateBuilder description(String description) {
        pipelineUpdate.setDescription(description);
        return this;
    }

    public PipelineUpdateBuilder createdBy(String createdBy) {
        pipelineUpdate.setCreatedBy(createdBy);
        return this;
    }

    public PipelineUpdateBuilder manifestFolderPath(String manifestFolderPath) {
        pipelineUpdate.setManifestFolderPath(manifestFolderPath);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PipelineUpdate build() {
        return pipelineUpdate;
    }
}