/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PipelineCreate 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5640522958788659207L;
    private String pipelineName;
    private String description;
    private String createdBy;
    private String manifestFolderPath;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("pipelineName")
    public String getPipelineName ( ) { 
        return this.pipelineName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("pipelineName")
    public void setPipelineName (String value) { 
        this.pipelineName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createdBy")
    public String getCreatedBy ( ) { 
        return this.createdBy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createdBy")
    public void setCreatedBy (String value) { 
        this.createdBy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("manifestFolderPath")
    public String getManifestFolderPath ( ) { 
        return this.manifestFolderPath;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("manifestFolderPath")
    public void setManifestFolderPath (String value) { 
        this.manifestFolderPath = value;
    }
 
}
