/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class PipelineBuilder {
    //the instance to build
    private Pipeline pipeline;

    /**
     * Default constructor to initialize the instance
     */
    public PipelineBuilder() {
        pipeline = new Pipeline();
    }

    public PipelineBuilder id(String id) {
        pipeline.setId(id);
        return this;
    }

    public PipelineBuilder pipelineName(String pipelineName) {
        pipeline.setPipelineName(pipelineName);
        return this;
    }

    public PipelineBuilder description(String description) {
        pipeline.setDescription(description);
        return this;
    }

    public PipelineBuilder createdBy(String createdBy) {
        pipeline.setCreatedBy(createdBy);
        return this;
    }

    public PipelineBuilder createdDate(String createdDate) {
        pipeline.setCreatedDate(createdDate);
        return this;
    }

    public PipelineBuilder manifestFolderPath(String manifestFolderPath) {
        pipeline.setManifestFolderPath(manifestFolderPath);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Pipeline build() {
        return pipeline;
    }
}