/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SMDSWorkflowPayloadBuilder {
    //the instance to build
    private SMDSWorkflowPayload sMDSWorkflowPayload;

    /**
     * Default constructor to initialize the instance
     */
    public SMDSWorkflowPayloadBuilder() {
        sMDSWorkflowPayload = new SMDSWorkflowPayload();
    }

    public SMDSWorkflowPayloadBuilder resourceTypeID(String resourceTypeID) {
        sMDSWorkflowPayload.setResourceTypeID(resourceTypeID);
        return this;
    }

    public SMDSWorkflowPayloadBuilder manifest(String manifest) {
        sMDSWorkflowPayload.setManifest(manifest);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SMDSWorkflowPayload build() {
        return sMDSWorkflowPayload;
    }
}