/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class SWPSWorkflowPayloadBuilder {
    //the instance to build
    private SWPSWorkflowPayload sWPSWorkflowPayload;

    /**
     * Default constructor to initialize the instance
     */
    public SWPSWorkflowPayloadBuilder() {
        sWPSWorkflowPayload = new SWPSWorkflowPayload();
    }

    public SWPSWorkflowPayloadBuilder resourceTypeID(String resourceTypeID) {
        sWPSWorkflowPayload.setResourceTypeID(resourceTypeID);
        return this;
    }

    public SWPSWorkflowPayloadBuilder manifest(String manifest) {
        sWPSWorkflowPayload.setManifest(manifest);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SWPSWorkflowPayload build() {
        return sWPSWorkflowPayload;
    }
}