/*
 * OsduR1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example;

import com.example.controllers.*;
import com.example.http.client.HttpClient;

public class OsduR1Client {
    /**
     * Singleton access to IngestionClient controller
     * @return	Returns the IngestionClientController instance 
     */
    public IngestionClientController getIngestionClient() {
        return IngestionClientController.getInstance();
    }

    /**
     * Singleton access to WorkflowAPI controller
     * @return	Returns the WorkflowAPIController instance 
     */
    public WorkflowAPIController getWorkflowAPI() {
        return WorkflowAPIController.getInstance();
    }

    /**
     * Singleton access to CollectionAPI controller
     * @return	Returns the CollectionAPIController instance 
     */
    public CollectionAPIController getCollectionAPI() {
        return CollectionAPIController.getInstance();
    }

    /**
     * Singleton access to DeliveryAPI controller
     * @return	Returns the DeliveryAPIController instance 
     */
    public DeliveryAPIController getDeliveryAPI() {
        return DeliveryAPIController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public OsduR1Client() {
    }

}